### ISSUE TITLE
Display month with leading 0

### ISSUE THREAD

**Issue by nielsk** [sachaos/todoist#10]
Months are afaik usually displayed with a leading zero when using "date". Like this: 17/06/12
todoist shows it like 17/6/12 - therefore you cannot do something like this: todoist l | fgrep `date +"%y/%m/%d"` (that's the syntax on FBSD). It would be great if you could display months like this or at least offer an option. Then one can add simple aliases for displaying tasks due "today" or "tomorrow"

**Comment by sachaos** [comment]
@nielsk Thanks you for your feedback.
I think it is most important in this product, how easy it is to integrate with UNIX tools.
So I fixed it on #11.
Thanks.

**Comment by nielsk** [comment]
Great, thanks a lot :)
