### ISSUE TITLE
No way to add/remove projects

### ISSUE THREAD

**Issue by nicksettoon** [sachaos/todoist#113]
I've written a set of functions to wrap the use of this program today in easy aliases. It allows for selecting and bulk deleting of multiple tasks, printing just tasks within a certain project, easily adding tasks by just their string and prompting for the desired project to store them in.
All I'm missing is the ability to create and delete projects, which is not a feature as far as I can tell.
I wish I could contribute at the moment, but I'm still at university.

**Comment by kenliu** [comment]
looks like this issue can be closed

**Comment by bytrangle** [comment]
How does one add a project? I see a command `add-project` in the `main.go` file, but when I run it, I got “No help topic for 'add-project'”.

**Comment by nicksettoon** [comment]
closing cause requested.
