### ISSUE TITLE
Move cache to .cache

### ISSUE THREAD

**Issue by pniedzwiedzinski** [sachaos/todoist#118]
Hey!
Thanks for this project I really enjoy using it. :heart: 

I think that it might be a good idea to move `~/.todoist.cache.json` to `~/.cache/todoist/cache.json`. The cache directory in home is pretty standard so why don't use it.

I would be happy to contribute on this

**Comment by MarcoDiFrancesco** [comment]
I'd also move `~/.todoist.config.json` to `~/.config/todoist/config.json`
