### ISSUE TITLE
unrecognized import path "context"

### ISSUE THREAD

**Issue by thefotios** [sachaos/todoist#12]
With a completely clean `GOPATH` I get the following error:

```
$ go get -v github.com/sachaos/todoist
package context: unrecognized import path "context" (import path does not begin with hostname)
```

Attached is the output if it helps as well as information about my `go` environment

```
$ go version
go version go1.6.4 linux/amd64

$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/flindiakos/.go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

[output.txt](https://github.com/sachaos/todoist/files/1068753/output.txt)

**Comment by thefotios** [comment]
It appears that this package was added in Go 1.7, so there may not be a way to workaround it, but at least the minimum version could be documented.

**Comment by sachaos** [comment]
@thefotios Thank you for your feedback.
Yes, This product require Golang 1.7 from v0.9.0.
I added note to README (https://github.com/sachaos/todoist#install) about requiring golang version.
