### ISSUE TITLE
How does modify work?

### ISSUE THREAD

**Issue by nielsk** [sachaos/todoist#13]
How does modify work?
For example I have a task that is due today and I want to move it to tomorrow. Thus I expected I just had to do this:
`todoist m 2238698186 -d '26/06/2017'`

But this doesn't work and only fails silently (task is still due today).

**Comment by nielsk** [comment]
Ok, it seems to work for projects, thus I guess this is a bug.

**Comment by sachaos** [comment]
Thanks for your bug report.
I'll fix this bug.

**Comment by sachaos** [comment]
It seems a bug of Todoist API.
When I called API with curl, it failed too.

There are same issue on official API repository.
https://github.com/Doist/todoist-api/issues/31

**Comment by nielsk** [comment]
Oh, ok. Then we have to wait apparently that it is fixed on Todoist a side.

**Comment by sachaos** [comment]
@nielsk This problem was solved!
I'm closing this issue.
