### ISSUE TITLE
[Feature request]  JSON output

### ISSUE THREAD

**Issue by kristijanhusak** [sachaos/todoist#130]
Hi,

is there a chance to add a JSON output format?

I want to create plugin for vim that would use this, but I cannot reliably parse csv. JSON would be super helpful.

**Comment by sachaos** [comment]
@kristijanhusak Yes. I think it is good feature.
Can you make the PR?

**Comment by kristijanhusak** [comment]
Yeah I can try to make it. Don't have much go experience.

**Comment by sachaos** [comment]
@kristijanhusak Thank you!
If I can get a PR, I'll merge it.

**Comment by kristijanhusak** [comment]
@sachaos It's a bit tricky to introduce json format because I don't know the property names. Writer gets only array of strings. I think this would require a bit of rewriting of other parts to send all data to the writer.
Do you maybe know a simpler solution?

**Comment by andreoliwa** [comment]
I started something very raw here: https://github.com/sachaos/todoist/pull/160
Please let me know if I'm on the right path. 🙂
