### ISSUE TITLE
Chocolatey

### ISSUE THREAD

**Issue by xmha97** [sachaos/todoist#131]
Hello,
I want to install [Todoist-CLI](https://github.com/sachaos/todoist) on Windows 10.
Please add this project to [Chocolatey](https://chocolatey.org/).
Chocolatey is a package manager for Windows.
Thanks.

**Comment by sachaos** [comment]
@xmha97 I think it is very good. But sorry, I don't have a Windows machine. 😢 
It is great If you can register this package to the project.

I think the documentation is https://chocolatey.org/docs/create-packages .

**Comment by xmha97** [comment]
Okay, I closed this issue, but I'll do it.
