### ISSUE TITLE
Make quick add support inline parsing

### ISSUE THREAD

**Issue by bowiechen** [sachaos/todoist#134]
It seems the difference between `add` (`a`) and `quick` (`q`) is that the former supports a bunch of parameters like `--priority` and `--project-name` but the latter doesn't. 

I think we could make `q` more helpful if we could implement a couple lightweight metadata parsing for specical todoist flags, the list as follows:

- [ ] **Priority** can be expressed using `pN` or `!!N`, where `N` is the priority value.
- [ ] **Project Name** can be expressed using `#project_name`.
- [ ] **Label** can be expressed using `@label`.

This will help further distinguish `q` from `a` and make `q` more like what is currently offered on Todoist.

**Comment by bowiechen** [comment]
After reading the code a bit more, I realized that my ask already work! The following have created expected tasks:
`todoist q '#Personal tmr 9am p3 q test'`
`todoist q '#Personal tmr 9am !!3 q test'`

Note that due to `#` and `!` being special characters in `bash`, user must enclose the string in quotes or manually escape the special characters.

cc @nick96 seems like #121 isn't necessary! =)

**Comment by bytrangle** [comment]
> `todoist q '#Personal tmr 9am p3 q test'`
> `todoist q '#Personal tmr 9am !!3 q test'`
Thanks for the tips, but this won't work if a project name contains multiple words, right?
