### ISSUE TITLE
Add documentation on peco autocompletion

### ISSUE THREAD

**Issue by jaredmo** [sachaos/todoist#141]
I'm not following how to setup peco from the README. Seems like there are some knowledge assumptions or gaps in the documentation.

**Comment by bytrangle** [comment]
> I'm not following how to setup peco from the README. Seems like there are some knowledge assumptions or gaps in the documentation.

Assuming that you installed this app with Homebrew, switch to Zshell if you haven't. You need zshell for it to work.
In your command line, simply run
`source $(brew --prefix)/share/zsh/site-functions/_todoist_peco` to enable peco for the app

Then try a command like `todoist l` to get all your tasks. Then type `Ctrl + x` to activate Peco, followed by `t t` to select task.
