### ISSUE TITLE
Unable to filter tasks by project when the project name contains multiple-words

### ISSUE THREAD

**Issue by bytrangle** [sachaos/todoist#142]
For example, I have two projects: Blogging and Build a CLI app.
If I want to retrieve tasks belong to the Blogging project, I can run this command with no problem:
`todoist l --filter '#Blogging'`
However, the same syntax for retrieving tasks from the Build a Cli app fails:
`todoist l --filter '#Build a Cli app`
It throws an error: `Filter error: syntax error 
For proper filter syntax see https://support.todoist.com/hc/en-us/articles/205248842-Filters'.

**Comment by elipavlov** [comment]
This is not solution, but to me works following, spell only first word of the project's name:

```bash
todoist l --filter '#Build'
```

Todoist docs says nothing about space character in the project names:
https://todoist.com/help/articles/filters

**Comment by eugeneware** [comment]
I've also having this issue. In my case my project is '#Machine Learning' but it throws a syntax error. Is this an API issue, or how the filtering is implemented in the golang code?

**Comment by bytrangle** [comment]
@eugeneware : IIRC this is a Todoist API issue. In case you don't have another project that contains the word **Machine**, you can filter for your **Machine Learning** project with the first word only. Example: 
```
todoist l -f '#Machine'
```

**Comment by eugeneware** [comment]
Thanks @bytrangle - I didn't realise it was a raw API issue, I saw a query parser in the source code and thought it might be due to the local logic in this tool. I'll use that as a work around for now. Thanks.

**Comment by Jamedjo** [comment]
https://www.todoist.com/help/articles/introduction-to-filters-V98wIH suggests a `\` can be used to escape spaces:

> Use special characters in project, section, or label names as regular characters.
>
>Filter tasks in projects, sections, or labels with two or more words in the name.
>
> e.g. #One \& Two
> e.g. #Shopping\ list
