### ISSUE TITLE
Is it required to use zsh to use this CLI?

### ISSUE THREAD

**Issue by scottpham** [sachaos/todoist#16]

**Comment by sachaos** [comment]
@scottpham No, you can use this command in other shell.
But, if you wish to use some keybindings with `todoist_functions.sh`, you need to use zsh.

Please read here.
https://github.com/sachaos/todoist#use-with-peco

**Comment by scottpham** [comment]
Oh I see! My problem was that I hadn't installed Go before this, so my GOPATH's bin wasn't on my path. Added that, and now I can access the `todoist` command
