### ISSUE TITLE
Options to change the time (YY/MM/DD) to the user's choices ?

### ISSUE THREAD

**Issue by TRNEEDANAME** [sachaos/todoist#169]

**Comment by HacDan** [comment]
@TRENEEDNAMME You can change the date format on lines 34 and 35 of the main.go file. 
https://github.com/sachaos/todoist/blob/45738fbdcbf5eb06face0640120b4ad4b46a3be7/main.go#L34-L35

And a bit more information on `time.Time`'s [Format()](https://pkg.go.dev/time#Time.Format).

**Comment by fgimian** [comment]
Yes please, I found the date format used by the tool a bit odd.

For example, instead of;

```
21/11/21(Sun) 21:33
```

I would much rather see

```
2021-11-21 (Sun) 21:33
```

I think the year is especially troublesome, would really love that to be YYYY.

Thanks so much for this awesome tool!
Fotis

**Comment by HacDan** [comment]
Solved in Pull Request: #181 

Feel free to cherry-pick and let me know how it goes. No reason to recompile the binary to change this option anymore.
