### ISSUE TITLE
can't find the binary to start the program in terminal

### ISSUE THREAD

**Issue by robinsrk** [sachaos/todoist#187]
I have installed the package from aur in arch linux. but can't execute the program as can't find the binary in system after installing. command "todoist" shows not found.

**Comment by HacDan** [comment]
Looks like the package maintainer for Arch renamed the binary to `todoist-cli` instead of just `todoist`. 

Some discussion was had in the comments on the [AUR](https://aur.archlinux.org/packages/todoist)

**Comment by kenliu** [comment]
Closing out this issue as there is no further action needed here, thanks for posting the information about the arch package.
