### ISSUE TITLE
Config file location on Mac + add --config flag

### ISSUE THREAD

**Issue by angelod1as** [sachaos/todoist#189]
## System:

- zsh
- macOs Monterey 12.4
- iTerm2

## Expected:

- The path `~/.config/todoist/config.json` to be read and interpreted by the `todoist` package.
- The `.json` file below applying colors every time the `todoist l` command is called

```json
{
  "token": "XXX", # Hidden
  "color": "true"
}

```

## Result:

- The `todoist l` command isn't called with color (also tried with `header` and `indent`)

## Hypothesis:

- The `config` file is not created in the correct place.
- The `config` file isn't well written

## Solution:

- Update `README` with location for the `config` file in `macOS` systems
- Addition of a flag `--config` or similar that creates/shows the location of the current config file
- Addition of a line that tells if any default flag is loaded from config file when running `todoist --help` or similar.

**Comment by HacDan** [comment]
Hey Angelo,

How did you install Todoist-CLI? I presume via Brew, correct? If you install from source, this issue has been resolved

**Comment by angelod1as** [comment]
Yes, via Brew.

I'm not a Go user and don't have $GOPATH setup. Building from build didn't work without $GOPATH. I hope this gets fixed in Brew as well.
