### ISSUE TITLE
Is this project still maintained/actively being developed?

### ISSUE THREAD

**Issue by kittivelae** [sachaos/todoist#197]
If so, are PR's welcome?

Thanks

**Comment by sachaos** [comment]
@kittivelae Hi. I'm owner.

I haven't been able to do maintenance because I don't have much time to do maintenance. Also, I don't use it myself now, so I don't have much motivation. If there is someone who would like to maintain it, I would like to welcome it as a member of the repository.

We accept PRs for critical issues such as: https://github.com/sachaos/todoist/labels/help%20wanted

**Comment by kittivelae** [comment]
Entirely reasonable ill try and take a look at some of the issues once i can get some time. Thanks for getting back to me :)

**Comment by dwainm** [comment]
@sachaos I still use this daily. I'd be happy to be more involved. I see there aren't any [help wanted] issues. 

How can I get more involved? Maybe a bug label?

**Comment by sachaos** [comment]
@dwainm Thank you! If you want to improve this project, I would like to welcome as a member of this project. I don't have time to review the PRs, if you want to involve this project, I'm very happy if you can review those and fix some bugs.

**Comment by sachaos** [comment]
@nabaco Thank you. It's nice idea. I'll add @kittivelae and @dwainm firstly.
If you don't want this, feel free to reject the request.

**Comment by kittivelae** [comment]
Cheers for this. I can't contribute code right now bc I'm busy with just
starting my PhD but I will do my best to look at pull requests where I can.

**Comment by dwainm** [comment]
Thanks for adding me @sachaos, I'll be happy to lend a hand, but only saw the invitation now and it has since expired. Please resend it when you have a moment.

**Comment by dwainm** [comment]
Thank you, I've accepted.

**Comment by kenliu** [comment]
I'll volunteer to help too if you are still open to adding maintainers

**Comment by sachaos** [comment]
@kenliu Thank you! I've sent an invitation to you.

**Comment by kenliu** [comment]
Now that we have a couple of volunteers I'm going to close out this issue.
