### ISSUE TITLE
Sync Issue due to int size

### ISSUE THREAD

**Issue by Kimau** [sachaos/todoist#2]
> json: cannot unmarshal number 9842555962 into Go value of type int

Looks like some data structs need to be upped to int64

**Comment by sachaos** [comment]
@Kimau Thanks for the report.
I added this problem to my todoist. 😃 
If you have time, call the Todoist API directly, grep the contents of the response with that number, do not tell me what value?

**Comment by Kimau** [comment]
`"live_notifications": [{
		"project_name": "Book",
		"created": ####,
		"is_deleted": 0,
		"seq_no": ###PROBLEM NUMBER####,
		"notification_key": "share_invitation_accepted_#####",
		"notification_type": "share_invitation_accepted",
		"invitation_id": #####,
		"project_id": #####,
		"id": 2968714,
		"from_uid": ####
	}]`

So it looks like live notifications seq_num

**Comment by sachaos** [comment]
@Kimau Thank you for your investigation. I fixed it. 😄 
If you still have problems, please let me know.
