### ISSUE TITLE
Invalid CSRF token

### ISSUE THREAD

**Issue by juggernaut451** [sachaos/todoist#201]
The project was working fine.. but suddently today it's showing 
`bad request: 403 Forbidden: Invalid CSRF token`

Below is the response form cloudfront
`{Status:"403 Forbidden", StatusCode:403, Proto:"HTTP/2.0", ProtoMajor:2, ProtoMinor:0, Header:http.Header{"Cache-Control":[]string{"no-cache"}, "Content-Length":[]string{"207"}, "Content-Type":[]string{"application/json"}, "Date":[]string{"Thu, 22 Dec 2022 18:56:04 GMT"}, "Referrer-Policy":[]string{"strict-origin-when-cross-origin"}, "Retry-After":[]string{"5"}, "Strict-Transport-Security":[]string{"max-age=31536000; includeSubDomains; preload"}, "Vary":[]string{"Accept-Encoding"}, "Via":[]string{"1.1 c6618f5186a4af698c105b9026bd0d68.cloudfront.net (CloudFront)"}, "X-Amz-Cf-Id":[]string{"QoQLbbLUOqYwxgdMYzkFs7TO2HmOSepZgaPbQqbjSwr7jaWwz8k3hA=="}, "X-Amz-Cf-Pop":[]string{"DEL54-P1"}, "X-Cache":[]string{"Error from cloudfront"}}`

**Comment by anastasiuspernat** [comment]
Same here! Just `Error: bad request: 403 Forbidden` starting this morning.

**Comment by mordax7** [comment]
Same.

**Comment by 0xWaleed** [comment]
Same

**Comment by ymzkryo** [comment]
Same

**Comment by dvragulin** [comment]
same :(

**Comment by anastasiuspernat** [comment]
This is what happened: https://groups.google.com/a/doist.com/g/todoist-api/c/sqrGTtCr-4A

The API must pass token in Headers instead of a parameter.

**Comment by sachaos** [comment]
@anastasiuspernat Thank you for the investigation.
I'll fix soon.

**Comment by sachaos** [comment]
I've fixed this issue in v0.18.0.
