### ISSUE TITLE
Bust the sync cache when the token changes

### ISSUE THREAD

**Issue by dwainm** [sachaos/todoist#212]
If you change your token (for the case of changing accounts or adding multiple accounts, see #211), we still return data from the previous account. 

The synced cache should compare the config token against that token stored in the sync storage. If no new one exists, we should still use the old sync, but if a new/different one is present, we should bust the cache and potentially call sync again.

**Comment by dwainm** [comment]
Thanks for the fix, @kenliu!

**Comment by kenliu** [comment]
thanks goes to @HacDan for the patch
