### ISSUE TITLE
Enable Discussions on this project

### ISSUE THREAD

**Issue by kenliu** [sachaos/todoist#213]
Hi @sachaos - now that we have multiple committers, it might be helpful to enable the Discussions feature on this repo so that we could start to talk about some topics related to how the code works or how we want to maintain this codebase. What do you think about that?

**Comment by sachaos** [comment]
@kenliu Thank you for the suggestion.
I think it's good idea.
I've enabled the discussions feature.

https://github.com/sachaos/todoist/discussions

**Comment by kenliu** [comment]
Thanks!
