### ISSUE TITLE
 sync produces Error: json: cannot unmarshal bool into Go struct field .reminders.is_deleted of type int

### ISSUE THREAD

**Issue by erstaples** [sachaos/todoist#214]
Just installed the todoist CLI. Unable to sync:

```
eric:~/ $ todoist sync
Error: json: cannot unmarshal bool into Go struct field .reminders.is_deleted of type int
```

**Comment by FlohGro-dev** [comment]
same error for me, I deleted the token in my config file but still didn't work.
also did a ```brew upgrade todoist``` before

**Comment by kenliu** [comment]
I tried to repro this by reinstalling 0.18.0 and deleting the config file and unable to reproduce on my Mac. Also tried reproducing this from latest master build on my linux machine.

**Comment by nv1t** [comment]
I think the problem arises in https://github.com/sachaos/todoist/blob/master/lib/sync.go#L53

If a task exists with a reminder, this struct is getting used and probably fails. By changing this integer to boolean, the error message is gone for me.

It seems weird, that every `isDeleted` is a boolean except for this line.

**Comment by kenliu** [comment]
@nv1t if you want to open a PR for this I can merge

**Comment by kenliu** [comment]
@sachaos can you do a 0.18.1 release for this change?

**Comment by erstaples** [comment]
Awesome, thanks for the fix!!!
