### ISSUE TITLE
v0.19.0 shows incorrect version in help and version output

### ISSUE THREAD

**Issue by hmnd** [sachaos/todoist#224]
In v0.19.0, the `--help` and `--version` commands output v0.18.0 as the installed version.

**Comment by kenliu** [comment]
@sachaos could you push a 0.20.0 release to resolve this version numbering issue?

**Comment by sachaos** [comment]
@kenliu Thank you.
I've released https://github.com/sachaos/todoist/releases/tag/v0.20.0

**Comment by kenliu** [comment]
looks great, thanks
