### ISSUE TITLE
Use $XDG_CONFIG_HOME for storing .todoist.config.json if set

### ISSUE THREAD

**Issue by Lindenk** [sachaos/todoist#23]
Not a big deal, but it would be nice to keep config files together and be standardized with most other *nix tools.

EDIT: Also using $XDG_DATA_HOME for .todoist.cache.json would be preferable too.

**Comment by sachaos** [comment]
@Lindenk Thank you for your feedback!
I didn't know $XDG_DATA_HOME.
I'll reconsider the location of the config file.

**Comment by wolframite** [comment]
Any updates on this issue?

**Comment by pniedzwiedzinski** [comment]
I'd be happy to implement this. I've accomplished cache home in #119 so this should be pretty the same.
