### ISSUE TITLE
Demo gifs no longer showing up

### ISSUE THREAD

**Issue by DArtagan** [sachaos/todoist#230]
Hello, I appreciate having this tool for the command line and I was looking to learn more about how you use it in your own workflow by watching the demo gifs in the README.  Unfortunately, their source no longer seems to be available.  Thanks!

**Comment by kenliu** [comment]
This looks like a temporary issue with GitHub itself.

**Comment by kenliu** [comment]
I looked into this a bit more and I think you are right, the original images are no longer available, as they pointed to (apparently) cached images.

**Comment by HacDan** [comment]
I've attached the two GIF's here from my local browser cache, although the links still work for me currently in a cache-cleared browser instance.


![7c399218-9ee6-11e6-974c-9dd59ced13a5](https://user-images.githubusercontent.com/155105/235566528-3a616aea-c4f8-4a72-a2ea-66b1e32ca9ba.gif)
![6ed99956-9ee6-11e6-85b0-7539393d803b](https://user-images.githubusercontent.com/155105/235566535-361ca340-f7ce-452d-b585-5b33c2853cc0.gif)

**Comment by kenliu** [comment]
LGTM too. Whatever was going one with GitHub caching images seems to be resolved.

Want to open a PR with these images linked from the readme? I think they really should be stored in an `img` folder and not linked directly to the cached images?

**Comment by HacDan** [comment]
I'm thinking an `assets` directory instead of images. It's less limiting and more inclusive of the `gifs` (or `gifs`potato potato).

**Comment by kenliu** [comment]
assets makes sense to me too
