### ISSUE TITLE
Adding a task doesn't honor project

### ISSUE THREAD

**Issue by manfredlotz** [sachaos/todoist#242]
todoist version 0.18.0 on Linux, EndeovourOs

`todoist-cl projects` shows

```
2314996357 #Inbox
2314996395 #Home 🏡
```

I do `todoist-cli add "this is for today" --date today -P 2314996395` and then

`todoist-cli l` and get

```
7174459210 p4                     #Inbox                      this is for today
```

I had expected

```
7174459210 p4                     #Home 🏡                      this is for today
```

Is this a bug or a pebkac?

**Comment by manfredlotz** [comment]
I should add that I am new to Todoist and I am not on Pro.

**Comment by manfredlotz** [comment]
It seems this is a bug in `add.go`.

If I change line 29 from

```
if item.ProjectID == "" {
```

to

```
 if item.ProjectID == "0" {
```

then it is working fine.

**Comment by tokane888** [comment]
Looks like wrong option position.
You should put option before "this is for today" like below

`todoist add --date today -P 2314996395 "this is for today"`

I think "this is for today" = `arguments` in todoist help.

```
❯ todoist --help
NAME:
   todoist - Todoist CLI Client

USAGE:
   todoist [global options] command [command options] [arguments...]

...
```

**Comment by manfredlotz** [comment]
Ok, accepted.
