### ISSUE TITLE
After install and inputting API token, app list 0 tasks

### ISSUE THREAD

**Issue by yezsaysme** [sachaos/todoist#33]
Difficult to debug the issue to see if the token was input wrong or there is a bug. First step is to check the API token is correct. Where is this stored?

**Comment by sachaos** [comment]
API token is stored in `~/.todoist.config.json` .

**Comment by yezsaysme** [comment]
Thanks, I checked the config and the api is entered correctly. 'todoist l' displays nothing (should show 3 tasks at the moment). Any other ideas to debug?

**Comment by sachaos** [comment]
See `~/.todoist.cache.json`, all items are cached here.
If there are no items, you should sync with todoist.com.
Please run `todoist sync` command.

**Comment by yezsaysme** [comment]
Ah, working now. Thanks for assistance!

**Comment by kostajh** [comment]
@sachaos it might be worth adding to the README. I was about to file a bug report, as I couldn't figure this out.

**Comment by sachaos** [comment]
@kostajh Thank you for your feedback.
I added help about `sync`. #42
