### ISSUE TITLE
Specify --color in global config?

### ISSUE THREAD

**Issue by kostajh** [sachaos/todoist#43]
Hi, I might be missing something obvious but I don't see how to default to `--color` for all my commands? I tried setting `"color": true` the config JSON, but that's not working. Could you please point me to the docs for that? Thanks!

**Comment by strangeman** [comment]
As I see, there is no way to set `color: true` in config. This is will be a good improvement.

**Comment by sachaos** [comment]
Shell alias would be satisfy the requirement. 

in your, .bashrc or .zshrc
```
alias todoist='todoist --color'
```

**Comment by sachaos** [comment]
And merged #44 
So I close this.
