### ISSUE TITLE
How to add todoist_functions?

### ISSUE THREAD

**Issue by mountwebs** [sachaos/todoist#45]
First of all, this is great software! However, it would make it a lot better with peco-functionality, and I can't seem to make it work. I have installed Peco. When I try to add todoist_functions.sh to .zshrc I just get this error:

```
-bash: zle: command not found
-bash: bindkey: command not found
-bash: zle: command not found
-bash: bindkey: command not found
-bash: zle: command not found
-bash: bindkey: command not found
-bash: zle: command not found
-bash: bindkey: command not found
-bash: zle: command not found
-bash: bindkey: command not found
-bash: zle: command not found
-bash: bindkey: command not found
-bash: zle: command not found
-bash: bindkey: command not found
```

Help is much appreciated!

Ps. I'm on a mac.

**Comment by sachaos** [comment]
@mountwebs Thank you!

You are using bash, use zsh, please.

**Comment by mountwebs** [comment]
Thank you! You are of course correct.
