### ISSUE TITLE
Compatible with oh-my-zsh?

### ISSUE THREAD

**Issue by Jestre** [sachaos/todoist#46]
I just discovered this, and instaledl both it and `peco` with `Homebrew` this morning.  A couple questions:

Is it possible to include the `todoist_functions.sh` file in the pieces installed via Homebrew?  That would make it easier to `source` and track.  

Regardless, I downloaded it and put it in /usr/local/share/todoist/.  I added the `source /usr/local/.../todoist_functions.sh` line to `.oh-my-zsh/custom/todoist.zsh` so it would be loaded, but after restarting the shell, none of the keyboard magic seems to happen.

I found issue #22 and tried to follow along, but when I hit `Ctrl-X tp` nothing happens, nor does anything happen for any of the other mappings.

Also, how does the command line prefill/examples work in the demo images?  Is that an available addon?

Thank you

**Comment by sachaos** [comment]
@Jestre I'm not oh-my-zsh user. So I'm not familiar with that.
Try to put whole code of `todoist_functions.sh` in `.oh-my-zsh/custom/todoist.zsh`not by `source`.
Or please check your todoist.zsh is loaded correctly by printing debug message by `echo` command.

**Comment by Jestre** [comment]
@sachaos Thanks for the reply.  I added an `echo` to ensure that the custom file was being processed, and that worked.  Also, while reading up on completions (are these technically completions, or just some kind of keyboard mapping functions?) I saw that oh-my-zsh calls `compinit` automatically when it is loaded, so all completions need to be added to the `.zshrc` file prior to o-m-z being called.  I moved the `source` command into the zshrc file, and still nothing, though when I added the `homeshick` completions, they do work:

    # User configuration
    source "/usr/local/share/todoist/todoist_functions.sh"
    fpath=($HOME/.homesick/repos/homeshick/completions $fpath)
    
    source $ZSH/oh-my-zsh.sh

So the last thing I tried after reading your note this morning was to remove my .zshrc and open a new term (iTerm 2) with a default zsh config.  After I source the funcs file, all works as in your documentation.  So it appears that o-m-z is somehow blocking these.

**Comment by sachaos** [comment]
@Jestre  Thank you for reporting.
I'll check the problem of working with o-m-z, if I have time.
Please report again, if you solved the problem.
Thank you.

**Comment by Jestre** [comment]
Well I don't know if I did anything in particular to cause it to start working, but after applying the iTerm2 update today this function started working, so I will close this ticket.  Thanks for the responses.

Now to figure out why `color` in the config.json file isn't working :)
