### ISSUE TITLE
Priority labels are backwards?

### ISSUE THREAD

**Issue by scottpeterson** [sachaos/todoist#49]
I believe within Todoist p1 = highest priority, down to p4 = lowest.

On the CL Todoist, 'todoist list --filter p1' shows me my p4 labeled tasks, and 'todoist list --filter p4' shows me my p1 labeled tasks.....

**Comment by yyolk** [comment]
I'm also seeing this, but apparently this is a quirk with the API. 

From https://developer.todoist.com/sync/v7/#items

```
The priority of the task (a number between 1 and 4, 4 for very urgent and 1 for natural). 
Note: Keep in mind that very urgent is the priority 1 on clients. So, p1 will return 4 in the API.
```

On my fork I've made a branch that shows this to me in the listing so I remember to remap, maybe someone get better implement this so as a user you still think of `!!1` as your high priority

**Comment by sachaos** [comment]
I fixed this in https://github.com/sachaos/todoist/pull/88
