### ISSUE TITLE
peco-todoist-date: gnu date is incompatible with bsd date

### ISSUE THREAD

**Issue by yanfali** [sachaos/todoist#5]
Hi @sachaos 

Awesome tool. I've been trying to use todoist_functions.sh but ran into trouble with ^xtd bindings with peco-todoist-date. It's using the bsd variant of `date` which supports `-v`. The gnu variant has `--date` and the format is similar but different. I added the following to my version, but I think there's probably a better way as they are only differ in one parameter.

```sh
function peco-todoist-date () {
    date -v 2>/dev/null >/dev/null
    if [ $? -eq 0 ] ; then
      local SELECTED_DATE="$(for ((i = 0; i <= 30; i++)); do date -v+${i}d '+%d/%m/%Y %a' ;done | peco | cut -d ' ' -f 1)"
    else
      local SELECTED_DATE="$(for ((i = 0; i <= 30; i++)); do date --date="${i} day" '+%d/%m/%Y %a' ;done | peco | cut -d ' ' -f 1)"
    fi
    insert-in-buffer "'${SELECTED_DATE}'" "-d"
}
```

**Comment by sachaos** [comment]
@yanfali 
Thanks issue.

I fixed it by DRY approach. https://github.com/sachaos/todoist/pull/6
Try it! 👍

**Comment by yanfali** [comment]
Works for me. Thank you!
