### ISSUE TITLE
Can't build on Ubuntu 18.04

### ISSUE THREAD

**Issue by claviola** [sachaos/todoist#53]
This is my attempt to build:

```
$ make install
dep ensure
go get golang.org/x/tools/cmd/goyacc
goyacc -o filter_parser.go filter_parser.y

conflicts: 4 shift/reduce
go install
# github.com/todoist
./add.go:24:41: client.Store.Projects.GetIDByName undefined (type todoist.Projects has no field or method GetIDByName)
./add.go:40:6: item.AutoReminder undefined (type todoist.Item has no field or method AutoReminder)
./delete.go:14:25: client.CompleteItemIDByPrefix undefined (type *todoist.Client has no field or method CompleteItemIDByPrefix)
./main.go:138:101: unknown field 'Color' in struct literal of type todoist.Config
./main.go:148:33: config.Color undefined (type *todoist.Config has no field or method Color)
./modify.go:21:24: client.CompleteItemIDByPrefix undefined (type *todoist.Client has no field or method CompleteItemIDByPrefix)
./modify.go:49:36: client.Store.Projects.GetIDByName undefined (type todoist.Projects has no field or method GetIDByName)
Makefile:3: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by sachaos** [comment]
@claviola Now, this project should be build with Go 1.11 or above.
What is your go version ?

**Comment by rounakj** [comment]
go version go1.9.3 linux/amd64

**Comment by Hexawolf** [comment]
@rounakj 
> go version go1.9.3 linux/amd64

See, your Go version is too low. I'd suggest using Go 1.12 or higher as described [here](https://tecadmin.net/install-go-on-ubuntu/). After that, you can just execute `go get github.com/sachaos/todoist`, easy!

**Comment by claviola** [comment]
I'd like to say that I no longer have building issues, however:

> See, your Go version is too low. I'd suggest using Go 1.12 or higher as described [here](https://tecadmin.net/install-go-on-ubuntu/), but set GOPATH to some place like `$HOME/.go`. After that, you can just execute `go get github.com/sachaos/todoist`, easy!

I'd suggest changing the ones in README.md, as cloning and running `make install` is not enough. I had issues with dependencies that I had to solve with `go get -u github.com/sachaos/todoist` (from *outside* the directory, for some reason). I think in the past this was handled by dep, but that doesn't seem to be the case anymore, right? Anyway, as my issue is fixed I'm closing this.
