### ISSUE TITLE
Plans to update to API v8?

### ISSUE THREAD

**Issue by MikeSperone** [sachaos/todoist#75]
I'm seeing that this project is using the todoist API v7:
https://github.com/sachaos/todoist/blob/master/lib/main.go#L15

Todoist is saying that v7 is deprecated and will be removed on July 31st - just over 2.5 months from me opening this issue:
https://developer.todoist.com/sync/v7/

Are there any plans to update to the todoist v8 API?  Or will this project be dead on August first?

**Comment by sachaos** [comment]
Thank you.
I didn't know that.
I'll handle this.

**Comment by vascowhite** [comment]
From the [Todoist docs](https://developer.todoist.com/sync/v7/#overview)

> Note that there is a newer version of this documentation for the Todoist API v8, and we strongly recommended that you use it or migrate your code to it, as the v7 is deprecated and will be removed on August 30th.

Is the change to v8 in progress?

I was thinking of installing this, but if it won't work after the end of this month, there isn't any point.

@sachaos, it would be a shame to abandon this, you've obvoiusly put a lot of time and effort into it and it looks like a great program.

**Comment by sachaos** [comment]
@dsalahutdinov 
I'm working on this now. I think it will be in time for the deadline.

**Comment by sachaos** [comment]
@vascowhite 
I'm working on this now. I think it will be in time for the deadline.
