### ISSUE TITLE
Unable to export with `--csv`

### ISSUE THREAD

**Issue by mbbroberg** [sachaos/todoist#76]
Hi! Thank you for this incredibly helpful utility. I use it on a regular basis 😄 

I want to export `todoist list` as a CSV and I receive an error: 

```bash
$ todoist list --csv
Incorrect Usage: flag provided but not defined: -csv

NAME:
   todoist list - Show all tasks

USAGE:
   todoist list [command options] [arguments...]

OPTIONS:
   --filter value, -f value  filter expression

Error: flag provided but not defined: -csv
```

Is this expected? About environment: 

* MacOS 
* Bash or zsh (I tried both) 
* todoist version 0.13.0

And again, thank you for your work!

**Comment by sachaos** [comment]
@mbbroberg `--csv` is global option so it must be put before subcommand.

e.g. `todoist --csv list`

**Comment by mbbroberg** [comment]
Ah, makes sense. Excuse the delay - thank you @sachaos for clarifying!
