### ISSUE TITLE
"todoist list" is empty

### ISSUE THREAD

**Issue by nielsk** [sachaos/todoist#78]
When I use todoist nothing gets returned
```
8:23:36 user@computer ~ todoist list
8:24:10 user@computer ~ todoist --debug list
8:25:26 user@computer ~ todoist --debug projects
8:25:31 user@computer ~ 
```
I already issued a new API-token
todoist version 0.13.1

**Comment by sachaos** [comment]
@nielsk Did you run `todoist sync` ?

**Comment by nielsk** [comment]
Thanks, that was it. Sorry for bothering you.
