### ISSUE TITLE
Listing items in the "Today" view?

### ISSUE THREAD

**Issue by adam-lee** [sachaos/todoist#79]
Sorry if this has been described somewhere.
I can run the list command to list all the open items, but a lot of times I *just* want to look at what I have to do *today*. I was hoping to see Today as a project, but it's not there. Is there a convenient way to do this? Thanks!

**Comment by sachaos** [comment]
@adam-lee You can list all today's tasks by `todoist list --filter today`.

**Comment by adam-lee** [comment]
@sachaos I feel so dumb. Don't know how I missed that ;)
