### ISSUE TITLE
./main.go:20:23: undefined: os.UserHomeDir

### ISSUE THREAD

**Issue by dotrosedotnet** [sachaos/todoist#82]
I'm on Ubuntu 16.04. I've been really excited to get this up and running, and have tried an awful lot today. I got it working in Docker, but I need it working natively to incorporate it into my workflow.

I finally got a whole bunch of it installed, but then it terminated with this error.

Any idea what could be causing this?

go version outputs:

go version go1.11.11 linux/amd64

I tried go 1.2.2 and that just spat out a whole slew of errors and got nothing done. I feel like I'm closer, for what that's worth! ;)

**Comment by sachaos** [comment]
@dotrosedotnet This software need go 1.12. https://github.com/sachaos/todoist#build-it-yourself

**Comment by dotrosedotnet** [comment]
okay, now it's gone through the install process, but there's no todoist command. running todoist results in "command not found"

Thanks so much for your help. I don't know why I'm having so much trouble!

**Comment by dotrosedotnet** [comment]
"which todoist" also results in "command not found"

**Comment by dotrosedotnet** [comment]
nevermind, I got it!
