### ISSUE TITLE
410 Gone when running todoist s

### ISSUE THREAD

**Issue by 2mill** [sachaos/todoist#95]
Hi, I am running into an issue where I am getting a 410 Gone Bad when I try to sync todoist CLI. Idk how to fix this myself.

**Comment by wizeman** [comment]
Which version are you using?
I think that if you update to `v0.14.0` (or to a newer commit), that problem should be fixed.

**Comment by 2mill** [comment]
I'm sitting on 13.1 from the AUR package

**Comment by wizeman** [comment]
@2mill Please try version 0.14.0, I believe it should fix your issue.

**Comment by wleoncio** [comment]
Same problem here. It does seem to be caused by an [out-of-date package](https://aur.archlinux.org/packages/todoist). Issue solved by using the [`todoist-git` package](https://aur.archlinux.org/packages/todoist-git) instead, which is currently on version 0.14.0.

**Comment by 2mill** [comment]
using todoist-git solved it, but for some reason it's still open
